name: Docs
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Awesome Pages Plugin
        run: pip install mkdocs-awesome-pages-plugin
      - name: Install Mkdocs Material
        run: pip install mkdocs-material
      - name: Generate docs
        run: |
          cp -rf README.md docs
          mkdocs gh-deploy --force
